version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_SECRET=Secret

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=huy221100
      - POSTGRES_DB=liantra
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
